# An ansible playbook that sets up a tricked-out vim/zsh/tmux environment
#
# Author: Luke Macken <lmacken@redhat.com>
---

- name: Bootstrapping developer environment
  hosts: all

  tasks:

  - name: Installing zsh, vim, git, tmux, etc.
    sudo: true
    action: apt name={{ item }} state=latest update_cache=yes
    with_items:
    - zsh
    - vim-nox
    - git
    - tmux
    - htop

  - name: Changing the default shell to zsh
    sudo: true
    action: user shell=/usr/bin/tmux user=abdulkadir

- name: Entering Plugin Nirvana
  hosts: all
  sudo: False

  tasks:

  - name: Backing up existing ~/.zshrc
    action: shell if [ -f ~/.zshrc ]; then mv ~/.zshrc ~/.zshrc.orig; fi

  - name: Installing oh-my-zsh (https://github.com/robbyrussell/oh-my-zsh)
    action: git repo=https://github.com/robbyrussell/oh-my-zsh dest=~/.oh-my-zsh

  - name: Creating new ~/.zshrc
    action: shell cp ~/.oh-my-zsh/templates/zshrc.zsh-template ~/.zshrc

  - name: Installing spf13-vim, The Ultimate Vim Distribution (http://vim.spf13.com)
    action: shell curl http://j.mp/spf13-vim3 -L -o - | sh

  - name: Setting zsh as default for tmux configuration
    action: shell echo "set -g default-command /usr/bin/zsh" > ~/.tmux.conf
