---

- shell: echo "export GOROOT=/usr/lib/go" >> ~/.zshrc
  args:
    executable: /usr/bin/zsh

- shell: mkdir -p ~/projects/oss/gopath
  args:
    executable: /usr/bin/zsh

- shell: echo "export GOPATH=~/projects/oss/gopath" >> ~/.zshrc
  args:
    executable: /usr/bin/zsh

- shell: echo "export PATH=$PATH:~/projects/oss/gopath/bin" >> ~/.zshrc
  args:
    executable: /usr/bin/zsh

- shell: mkdir ~/.tmuxinator
  args:
    executable: /usr/bin/zsh
    creates: ~/.tmuxinator

- copy: src=files/go-hamms.yml dest=~/.tmuxinator/go-hamms.yml
