---

- name: Adding docker apt-source-key
  sudo: true
  action: apt_key keyserver=hkp://keyserver.ubuntu.com:80 id=36A1D7869245C8950F966E92D8576A8BA88D21E9 state=present

- name: Adding docker apt-source
  sudo: true
  action: shell echo "deb https://get.docker.com/ubuntu docker main" > /etc/apt/sources.list.d/docker.list

- name: Adding chrome apt-source-key
  sudo: true
  action: wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -

- name: Adding chrome apt-source
  sudo: true
  action: shell echo "deb http://dl.google.com/linux/chrome/deb/ stable main" > /etc/apt/sources.list.d/google-chrome.list

- name: Adding heroku apt-source
  sudo: true
  action: shell echo "deb http://toolbelt.heroku.com/ubuntu ./" > /etc/apt/sources.list.d/heroku.list

- name: Adding apt-fast apt-source
  sudo: true
  action: apt_repository repo='ppa:saiarcot895/myppa' state=present

- name: Adding network-speed-indicator apt-source
  sudo: true
  action: apt_repository repo='ppa:nilarimogard/webupd8' state=present

- name: Adding java8 apt-source
  sudo: true
  action: apt_repository repo='ppa:webupd8team/java' state=present

- shell: curl -sL https://deb.nodesource.com/setup | sudo bash -

- name: Installing zsh, vim, git, tmux, etc.
  sudo: true
  action: apt name={{ item }} state=latest update_cache=yes
  with_items:
  - zsh
  - vim-gtk
  - git
  - tmux
  - htop
  - curl
  - mercurial
  - make
  - binutils
  - bison
  - gcc
  - build-essential
  - wget
  - ca-certificates
  - bzr
  - axel
  - tree
  - ctags
  - python-dev
  - ruby2.1
  - ruby2.1-dev
  - cmake
  - dconf-cli
  - lxc-docker
  - nodejs
  - oracle-java8-installer
  - oracle-java8-set-default
  - python2.7
  - indicator-netspeed
  - google-chrome-stable
  - account-plugin-*
  - libreadline-dev
  - heroku-toolbelt

- name: updating pip
  sudo: true
  action: shell easy_install -U pip

- name:  installing pyinotify
  sudo: true
  action: shell pip install pyinotify

- name: installing when-changed
  sudo: true
  action: shell pip install https://github.com/joh/when-changed/archive/master.zip

- name: installing tmuxinator
  sudo: true
  action: shell gem install tmuxinator

- name: installing travis-ci client
  sudo: true
  action: shell gem install travis -v 1.7.5 --no-rdoc --no-ri
