---

- name: Changing the default shell to tmux
  sudo: true
  action: user shell=/usr/bin/tmux user=abdulkadir

- name: Backing up existing ~/.zshrc
  action: shell if [ -f ~/.zshrc ]; then mv ~/.zshrc ~/.zshrc.orig; fi

- shell: git repo=https://github.com/robbyrussell/oh-my-zsh dest=~/.oh-my-zsh
  args:
    creates: ~/.oh-my-zsh

- shell: cp ~/.oh-my-zsh/templates/zshrc.zsh-template ~/.zshrc
  args:
    creates: ~/.zshrc

- shell: echo "export EDITOR=vim" >> ~/.zshrc

- copy: src=files/tmux.conf dest=~/.tmux.conf

- shell: mkdir ~/.tmux
  args:
    creates: ~/.tmux

- copy: src=files/tmux.dev dest=~/.tmux/dev
